package com.tess.enums;

public enum NotificationType {
    APPLICATION_SUBMITTED,
    APPLICATION_ACCEPTED,
    APPLICATION_REJECTED,
    INTERVIEW_SCHEDULED,
    INTERVIEW_CANCELLED,
    MESSAGE_RECEIVED,
    JOB_POSTED,
    ACCOUNT_DEACTIVATED
}
